import '../constants/market_categories.dart';
import '../constants/shoe_sizes.dart';
import '../models/category_field.dart';

abstract final class CategoryPostingSchemas {
  static CategoryPostingSchema forCategory(String category) =>
      _schemas[category] ?? _schemas['Other']!;

  static const _brand = CategoryField(
    key: 'brand',
    label: 'Brand',
    hint: 'e.g. Samsung, Apple, JBL',
    required: true,
  );

  static const _model = CategoryField(
    key: 'model',
    label: 'Model',
    hint: 'e.g. Galaxy Buds 2, AirPods Pro',
  );

  static final _schemas = <String, CategoryPostingSchema>{
    'Electronics & Gadgets': CategoryPostingSchema(
      category: 'Electronics & Gadgets',
      kind: ListingKind.product,
      titleHint: 'JBL Flip 6 speaker — barely used',
      descriptionHint:
          'Mention age, battery life, accessories included, and any defects.',
      descriptionChecklist: [
        'Brand and exact model',
        'How long you have used it',
        'Battery health or power performance',
        'Original box, charger, and accessories included',
        'Known scratches, faults, or repairs',
        'Why you are selling',
      ],
      photoTips: [
        'Front and back of the device',
        'Serial or model label if visible',
        'Accessories laid out together',
        'Any scratches or wear close-up',
      ],
      fields: [
        _brand,
        _model,
        const CategoryField(
          key: 'warranty',
          label: 'Warranty status',
          hint: 'Select warranty status',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['No warranty', 'Active warranty', 'Expired warranty'],
        ),
        const CategoryField(
          key: 'accessories',
          label: 'Included accessories',
          hint: 'Box, charger, cables, case...',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 180',
    ),
    'Phones & Tablets': CategoryPostingSchema(
      category: 'Phones & Tablets',
      kind: ListingKind.product,
      titleHint: 'iPhone 13 128GB — 89% battery health',
      descriptionHint:
          'Buyers need storage, battery health, network lock, and cosmetic condition.',
      descriptionChecklist: [
        'Brand, model, storage, and color',
        'Battery health percentage',
        'Face ID / fingerprint / screen condition',
        'Network unlocked or locked',
        'iCloud/Google account removed',
        'Cracks, dents, or repair history',
      ],
      photoTips: [
        'Front screen on and back panel',
        'Battery health screenshot',
        'Ports and corners close-up',
        'IMEI/settings screen if comfortable sharing',
      ],
      fields: [
        _brand,
        _model,
        const CategoryField(
          key: 'storage',
          label: 'Storage',
          hint: 'e.g. 128GB',
          required: true,
        ),
        const CategoryField(
          key: 'battery_health',
          label: 'Battery health',
          hint: 'e.g. 89%',
          required: true,
        ),
        const CategoryField(
          key: 'network',
          label: 'Network status',
          hint: 'Select network status',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Unlocked', 'Locked', 'Wi-Fi only (tablet)'],
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 3200',
    ),
    'Computers & Accessories': CategoryPostingSchema(
      category: 'Computers & Accessories',
      kind: ListingKind.product,
      titleHint: 'MacBook Air M1 — 8GB/256GB with charger',
      descriptionHint:
          'Include specs, OS version, battery cycles, and what is included.',
      descriptionChecklist: [
        'Brand, model, processor, RAM, and storage',
        'Operating system version',
        'Battery cycle count or health',
        'Keyboard, screen, and hinge condition',
        'Charger, bag, or extras included',
        'Any faults or recent repairs',
      ],
      photoTips: [
        'Laptop open and closed',
        'Keyboard and screen close-up',
        'About This Mac / system specs screenshot',
        'Charger and accessories',
      ],
      fields: [
        _brand,
        _model,
        const CategoryField(
          key: 'specs',
          label: 'Key specs',
          hint: 'e.g. M1, 8GB RAM, 256GB SSD',
          required: true,
        ),
        const CategoryField(
          key: 'os_version',
          label: 'OS version',
          hint: 'e.g. macOS Sonoma, Windows 11',
        ),
        const CategoryField(
          key: 'battery_cycles',
          label: 'Battery cycles / health',
          hint: 'e.g. 214 cycles',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 4200',
    ),
    'Fashion & Clothing': CategoryPostingSchema(
      category: 'Fashion & Clothing',
      kind: ListingKind.product,
      titleHint: 'Nike tech fleece hoodie — size L, worn twice',
      descriptionHint:
          'State size clearly, fit notes, fabric, and how often it was worn.',
      descriptionChecklist: [
        'Brand and item type',
        'Size and fit (true to size / oversized)',
        'Fabric and color',
        'Times worn or if brand new with tags',
        'Stains, fading, pilling, or damage',
        'Washing/care notes',
      ],
      photoTips: [
        'Full front and back flat lay',
        'Brand tag and size label',
        'Fabric texture close-up',
        'Any flaws clearly visible',
      ],
      fields: [
        _brand,
        const CategoryField(
          key: 'size',
          label: 'Size',
          hint: 'e.g. L, 32 waist, EU 42',
          required: true,
        ),
        const CategoryField(
          key: 'gender',
          label: 'Fit / style',
          hint: 'Select fit',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Men', 'Women', 'Unisex'],
        ),
        const CategoryField(
          key: 'material',
          label: 'Material',
          hint: 'e.g. cotton, denim, polyester',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 120',
      conditionOptions: ['New with tags', 'Like new', 'Good', 'Fair'],
    ),
    'Shoes & Bags': CategoryPostingSchema(
      category: 'Shoes & Bags',
      kind: ListingKind.product,
      titleHint: 'Adidas Campus 00s — UK 8, great condition',
      descriptionHint:
          'Include insole wear, sole condition, and authenticity cues. Size is captured separately below.',
      descriptionChecklist: [
        'Brand and model',
        'Insole and sole wear',
        'Creasing, scuffs, or odor issues',
        'Original box or dust bag included',
        'Authenticity notes if relevant',
      ],
      photoTips: [
        'Side, top, and sole views',
        'Size label inside tongue or insole',
        'Insole and heel wear',
        'Box or receipt if available',
      ],
      fields: [
        const CategoryField(
          key: 'item_type',
          label: 'Item type',
          hint: 'Select item type',
          required: true,
          type: CategoryFieldType.dropdown,
          options: [
            'Sneakers',
            'Formal shoes',
            'Sandals',
            'Backpack',
            'Handbag',
            'Other bag',
          ],
        ),
        _brand,
        _model,
        const CategoryField(
          key: 'shoe_size',
          label: 'Shoe size',
          hint: 'Pick fit, size system, and size',
          required: true,
          type: CategoryFieldType.shoeSize,
          visibleWhenKey: 'item_type',
          visibleWhenValues: ShoeSizes.shoeItemTypes,
        ),
        const CategoryField(
          key: 'bag_capacity',
          label: 'Capacity / size',
          hint: 'e.g. 25L backpack, 14" laptop sleeve',
          required: true,
          visibleWhenKey: 'item_type',
          visibleWhenValues: ShoeSizes.bagItemTypes,
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 280',
      conditionOptions: ['New with tags', 'Like new', 'Good', 'Fair'],
    ),
    'Beauty & Personal Care': CategoryPostingSchema(
      category: 'Beauty & Personal Care',
      kind: ListingKind.product,
      titleHint: 'The Ordinary serum bundle — 80% left',
      descriptionHint:
          'Buyers need remaining amount, expiry, hygiene, and storage details.',
      descriptionChecklist: [
        'Brand and product name',
        'Remaining amount or fill level',
        'Expiry or PAO date if visible',
        'Sealed or opened',
        'Storage conditions',
        'Skin type suitability if known',
      ],
      photoTips: [
        'Front label with product name',
        'Fill level or weight',
        'Expiry date close-up',
        'Batch of items if selling bundle',
      ],
      fields: [
        _brand,
        const CategoryField(
          key: 'product_name',
          label: 'Product name',
          hint: 'e.g. Niacinamide 10% + Zinc 1%',
          required: true,
        ),
        const CategoryField(
          key: 'remaining',
          label: 'Remaining amount',
          hint: 'e.g. 80% full, half bottle',
          required: true,
        ),
        const CategoryField(
          key: 'sealed',
          label: 'Seal status',
          hint: 'Select seal status',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Sealed', 'Opened', 'Tester'],
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 45',
      conditionOptions: ['Sealed', 'Opened — like new', 'Opened — used'],
    ),
    'Books & Stationery': CategoryPostingSchema(
      category: 'Books & Stationery',
      kind: ListingKind.product,
      titleHint: 'Engineering Mathematics — 4th edition',
      descriptionHint:
          'Include course, edition, author, highlighting, and missing pages.',
      descriptionChecklist: [
        'Book title and author',
        'Edition and publication year',
        'Course or level it supports',
        'Highlighting, notes, or missing pages',
        'Cover and spine condition',
        'Whether CD/code is included',
      ],
      photoTips: [
        'Front cover and spine',
        'Edition and ISBN page',
        'Sample pages showing notes/highlighting',
        'Any damage to corners',
      ],
      fields: [
        const CategoryField(
          key: 'title_author',
          label: 'Title / author',
          hint: 'e.g. Calculus — Stewart',
          required: true,
        ),
        const CategoryField(
          key: 'edition',
          label: 'Edition',
          hint: 'e.g. 4th edition, 2022',
          required: true,
        ),
        const CategoryField(
          key: 'course',
          label: 'Course / level',
          hint: 'e.g. MATH 201, Level 200',
        ),
        const CategoryField(
          key: 'isbn',
          label: 'ISBN',
          hint: 'Optional but helpful',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 45',
      conditionOptions: ['Like new', 'Light notes', 'Heavy notes', 'Worn cover'],
    ),
    'Courses & Notes': CategoryPostingSchema(
      category: 'Courses & Notes',
      kind: ListingKind.product,
      titleHint: 'ECON 101 lecture notes + past questions',
      descriptionHint:
          'Clarify semester, lecturer, format, completeness, and legality.',
      descriptionChecklist: [
        'Course code and title',
        'Semester / academic year',
        'Lecturer or class section if relevant',
        'Format: handwritten, typed, PDF, slides',
        'Topics covered and completeness',
        'Whether past questions or marking guides are included',
      ],
      photoTips: [
        'Table of contents or first pages',
        'Sample notes page',
        'Past questions cover if included',
        'Digital folder screenshot for PDF bundles',
      ],
      fields: [
        const CategoryField(
          key: 'course_code',
          label: 'Course code',
          hint: 'e.g. CS 101',
          required: true,
        ),
        const CategoryField(
          key: 'semester',
          label: 'Semester / year',
          hint: 'e.g. 2025/2026 Sem 1',
          required: true,
        ),
        const CategoryField(
          key: 'format',
          label: 'Format',
          hint: 'Select format',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Printed', 'PDF', 'Handwritten scans', 'Slides only', 'Mixed bundle'],
        ),
        const CategoryField(
          key: 'includes',
          label: 'Includes',
          hint: 'Notes, PQ, tutorials...',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 25',
      showCondition: false,
    ),
    'Food & Snacks': CategoryPostingSchema(
      category: 'Food & Snacks',
      kind: ListingKind.food,
      titleHint: 'Homemade beef pies — 6 pack, pickup today',
      descriptionHint:
          'State freshness, ingredients, allergens, and pickup window.',
      descriptionChecklist: [
        'What is included and serving size',
        'Homemade or store-bought',
        'Ingredients and allergens',
        'Prepared date and best consumed by',
        'Pickup time window',
        'Packaging and hygiene practices',
      ],
      photoTips: [
        'Full portion photo',
        'Packaging or label',
        'Ingredients list if homemade',
      ],
      fields: [
        const CategoryField(
          key: 'food_type',
          label: 'Food type',
          hint: 'e.g. pies, jollof pack, snack box',
          required: true,
        ),
        const CategoryField(
          key: 'quantity',
          label: 'Quantity / serving',
          hint: 'e.g. 6 pieces, 1 lunch box',
          required: true,
        ),
        const CategoryField(
          key: 'freshness',
          label: 'Freshness window',
          hint: 'e.g. pickup today by 6pm',
          required: true,
        ),
        const CategoryField(
          key: 'allergens',
          label: 'Allergens',
          hint: 'e.g. contains peanuts, dairy',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 35',
      showCondition: false,
    ),
    'Hostel & Room Essentials': CategoryPostingSchema(
      category: 'Hostel & Room Essentials',
      kind: ListingKind.product,
      titleHint: 'Mini fridge for hostel — works perfectly',
      descriptionHint:
          'Mention dimensions, power needs, age, and pickup help if heavy.',
      descriptionChecklist: [
        'Item type and brand if any',
        'Dimensions or capacity',
        'How long used and working condition',
        'Power requirements or installation needs',
        'Pickup logistics for bulky items',
        'Reason for selling',
      ],
      photoTips: [
        'Full item photo',
        'Label or capacity marking',
        'Plug and wear points',
        'Size reference object for scale',
      ],
      fields: [
        const CategoryField(
          key: 'item_type',
          label: 'Item type',
          hint: 'e.g. fridge, fan, mirror, kettle',
          required: true,
        ),
        const CategoryField(
          key: 'dimensions',
          label: 'Dimensions / capacity',
          hint: 'e.g. 45L, 60 x 40 cm',
        ),
        const CategoryField(
          key: 'power',
          label: 'Power / setup',
          hint: 'e.g. 220V, no installation needed',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 250',
    ),
    'Furniture': CategoryPostingSchema(
      category: 'Furniture',
      kind: ListingKind.product,
      titleHint: 'Study desk with drawer — 100 x 50 cm',
      descriptionHint:
          'Include material, dimensions, assembly state, and pickup help.',
      descriptionChecklist: [
        'Furniture type and material',
        'Exact dimensions (L x W x H)',
        'Assembly required or ready to use',
        'Scratches, wobble, or damage',
        'Whether disassembly/pickup help is available',
        'Meetup location on campus',
      ],
      photoTips: [
        'Full furniture shot',
        'Close-up of material and edges',
        'Drawer/shelf functionality',
        'Tape measure in frame for scale',
      ],
      fields: [
        const CategoryField(
          key: 'furniture_type',
          label: 'Furniture type',
          hint: 'e.g. desk, chair, shelf',
          required: true,
        ),
        const CategoryField(
          key: 'material',
          label: 'Material',
          hint: 'e.g. wood, metal, plastic',
          required: true,
        ),
        const CategoryField(
          key: 'dimensions',
          label: 'Dimensions',
          hint: 'e.g. 100 x 50 x 75 cm',
          required: true,
        ),
        const CategoryField(
          key: 'assembly',
          label: 'Assembly',
          hint: 'Select assembly state',
          type: CategoryFieldType.dropdown,
          options: ['Fully assembled', 'Needs assembly', 'Can disassemble for pickup'],
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 180',
    ),
    'Sports & Fitness': CategoryPostingSchema(
      category: 'Sports & Fitness',
      kind: ListingKind.product,
      titleHint: 'Adjustable dumbbells — pair, 20kg total',
      descriptionHint:
          'Include sport type, weight/size, wear, and safety condition.',
      descriptionChecklist: [
        'Sport or activity type',
        'Brand, weight, or size',
        'Usage frequency and wear',
        'Safety issues or missing parts',
        'Accessories included',
        'Pickup or carry notes',
      ],
      photoTips: [
        'Full equipment photo',
        'Weight label or size marking',
        'Grip/wear areas',
        'Accessories grouped together',
      ],
      fields: [
        const CategoryField(
          key: 'sport_type',
          label: 'Sport / activity',
          hint: 'e.g. gym, football, yoga',
          required: true,
        ),
        _brand,
        const CategoryField(
          key: 'size_weight',
          label: 'Size / weight',
          hint: 'e.g. UK 9 boots, 20kg pair',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 150',
    ),
    'Services & Gigs': CategoryPostingSchema(
      category: 'Services & Gigs',
      kind: ListingKind.service,
      titleHint: 'Logo design for campus clubs — 48h delivery',
      descriptionHint:
          'Explain deliverables, timeline, revisions, and what buyer must provide.',
      descriptionChecklist: [
        'Service type and deliverables',
        'Turnaround time',
        'Number of revisions included',
        'What the buyer must provide',
        'Portfolio or past work examples',
        'Payment and delivery method',
      ],
      photoTips: [
        'Portfolio samples or mockups',
        'Before/after examples if applicable',
        'Service menu graphic if you have one',
      ],
      fields: [
        const CategoryField(
          key: 'service_type',
          label: 'Service type',
          hint: 'e.g. design, tutoring, photography',
          required: true,
        ),
        const CategoryField(
          key: 'turnaround',
          label: 'Turnaround time',
          hint: 'e.g. 48 hours, same day',
          required: true,
        ),
        const CategoryField(
          key: 'deliverables',
          label: 'Deliverables',
          hint: 'e.g. 2 logo concepts + PNG/SVG',
          required: true,
        ),
        const CategoryField(
          key: 'revisions',
          label: 'Revisions included',
          hint: 'e.g. 2 free revisions',
        ),
      ],
      priceLabel: 'Starting price (GHS)',
      priceHint: 'e.g. 80 per logo',
      showCondition: false,
    ),
    'Tickets & Events': CategoryPostingSchema(
      category: 'Tickets & Events',
      kind: ListingKind.ticket,
      titleHint: 'Homecoming concert ticket — 15 Dec',
      descriptionHint:
          'Include event, date, venue, seat/section, and transfer method.',
      descriptionChecklist: [
        'Event name and date',
        'Venue and campus gate/time',
        'Seat, section, or ticket tier',
        'Transfer method (app, PDF, wristband)',
        'Original price and reason for sale',
        'ID requirements at entry',
      ],
      photoTips: [
        'Ticket screenshot with sensitive info blurred',
        'Event poster',
        'Seat/section details',
      ],
      fields: [
        const CategoryField(
          key: 'event_name',
          label: 'Event name',
          hint: 'e.g. SRC Week concert',
          required: true,
        ),
        const CategoryField(
          key: 'event_date',
          label: 'Event date',
          hint: 'e.g. 15 Dec 2026, 7pm',
          required: true,
        ),
        const CategoryField(
          key: 'venue',
          label: 'Venue',
          hint: 'e.g. Great Hall',
          required: true,
        ),
        const CategoryField(
          key: 'ticket_type',
          label: 'Ticket type',
          hint: 'e.g. VIP, regular, early bird',
          required: true,
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 50',
      showCondition: false,
    ),
    'Transportation': CategoryPostingSchema(
      category: 'Transportation',
      kind: ListingKind.product,
      titleHint: 'Campus bicycle — 6 months old',
      descriptionHint:
          'Include vehicle type, mileage/age, brakes, tires, and safety gear.',
      descriptionChecklist: [
        'Vehicle or service type',
        'Age, mileage, or route details',
        'Mechanical condition and recent service',
        'Included helmet/lock/accessories',
        'Pickup or test ride arrangements',
        'Any repairs needed',
      ],
      photoTips: [
        'Full side profile',
        'Tires, chain, and brakes close-up',
        'Odometer or serial if applicable',
        'Helmet/lock included',
      ],
      fields: [
        const CategoryField(
          key: 'transport_type',
          label: 'Type',
          hint: 'Select type',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Bicycle', 'Scooter', 'Skateboard', 'Carpool seat', 'Parking pass', 'Other'],
        ),
        const CategoryField(
          key: 'age_mileage',
          label: 'Age / mileage',
          hint: 'e.g. 6 months, 120 km',
        ),
        const CategoryField(
          key: 'condition_notes',
          label: 'Mechanical condition',
          hint: 'e.g. new brakes, needs tire pump',
          required: true,
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 450',
    ),
    'Health & Wellness': CategoryPostingSchema(
      category: 'Health & Wellness',
      kind: ListingKind.product,
      titleHint: 'Yoga mat + resistance bands bundle',
      descriptionHint:
          'State product type, sealed/opened status, and expiry if applicable.',
      descriptionChecklist: [
        'Product type and brand',
        'Sealed or opened status',
        'Expiry date if consumable',
        'Recommended use',
        'Hygiene and storage notes',
        'Medical disclaimers if relevant',
      ],
      photoTips: [
        'Product front label',
        'Expiry or batch code',
        'Bundle contents laid out',
      ],
      fields: [
        const CategoryField(
          key: 'product_type',
          label: 'Product type',
          hint: 'e.g. supplements, yoga mat, first aid kit',
          required: true,
        ),
        _brand,
        const CategoryField(
          key: 'sealed',
          label: 'Seal status',
          hint: 'Select seal status',
          type: CategoryFieldType.dropdown,
          options: ['Sealed', 'Opened', 'Not applicable'],
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 60',
      conditionOptions: ['Sealed', 'Opened — unused', 'Opened — used'],
    ),
    'Art & Crafts': CategoryPostingSchema(
      category: 'Art & Crafts',
      kind: ListingKind.product,
      titleHint: 'Hand-painted campus skyline canvas — A3',
      descriptionHint:
          'Mention medium, dimensions, handmade details, and framing.',
      descriptionChecklist: [
        'Art type and medium',
        'Dimensions and framing status',
        'Handmade or print details',
        'Inspiration or subject',
        'Care and handling notes',
        'Commission availability if relevant',
      ],
      photoTips: [
        'Full artwork straight-on',
        'Texture/brushwork close-up',
        'Frame or back mounting',
        'Size reference in frame',
      ],
      fields: [
        const CategoryField(
          key: 'art_type',
          label: 'Art type',
          hint: 'e.g. painting, print, crochet',
          required: true,
        ),
        const CategoryField(
          key: 'medium',
          label: 'Medium',
          hint: 'e.g. acrylic on canvas',
          required: true,
        ),
        const CategoryField(
          key: 'dimensions',
          label: 'Dimensions',
          hint: 'e.g. A3, 30 x 40 cm',
          required: true,
        ),
        const CategoryField(
          key: 'handmade',
          label: 'Handmade',
          hint: 'Select',
          type: CategoryFieldType.dropdown,
          options: ['Handmade', 'Print', 'Mixed'],
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 200',
    ),
    'Baby & Kids': CategoryPostingSchema(
      category: 'Baby & Kids',
      kind: ListingKind.product,
      titleHint: 'Baby stroller — clean, folds easily',
      descriptionHint:
          'Include age range, safety condition, cleanliness, and missing parts.',
      descriptionChecklist: [
        'Item type and recommended age',
        'Brand and model if known',
        'Safety straps, brakes, or locks working',
        'Cleanliness and stain notes',
        'Missing parts or manuals',
        'Smoke-free / pet-free home if relevant',
      ],
      photoTips: [
        'Full item assembled',
        'Safety features close-up',
        'Fabric/seat condition',
        'Folded size if applicable',
      ],
      fields: [
        const CategoryField(
          key: 'item_type',
          label: 'Item type',
          hint: 'e.g. stroller, toy, clothes',
          required: true,
        ),
        const CategoryField(
          key: 'age_range',
          label: 'Age range',
          hint: 'e.g. 0-12 months, 3-5 years',
          required: true,
        ),
        _brand,
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 300',
    ),
    'Pets & Supplies': CategoryPostingSchema(
      category: 'Pets & Supplies',
      kind: ListingKind.product,
      titleHint: 'Aquarium setup — 40L with filter',
      descriptionHint:
          'State pet type, brand, size, hygiene, and what is included.',
      descriptionChecklist: [
        'Pet type or supply category',
        'Brand and size/capacity',
        'Cleanliness and usage duration',
        'Included accessories',
        'Health/safety notes for live pets',
        'Pickup and transport notes',
      ],
      photoTips: [
        'Full setup or product',
        'Label and capacity',
        'Included accessories',
        'Cleanliness close-up',
      ],
      fields: [
        const CategoryField(
          key: 'pet_type',
          label: 'Pet / supply type',
          hint: 'e.g. fish tank, dog bed, cat food',
          required: true,
        ),
        _brand,
        const CategoryField(
          key: 'size',
          label: 'Size / capacity',
          hint: 'e.g. 40L tank, 5kg bag',
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 220',
    ),
    'Jobs & Internships': CategoryPostingSchema(
      category: 'Jobs & Internships',
      kind: ListingKind.job,
      titleHint: 'Campus barista — part-time weekends',
      descriptionHint:
          'Include role, pay, hours, requirements, and how to apply.',
      descriptionChecklist: [
        'Role title and employer type',
        'Paid or unpaid and pay range',
        'Hours per week and schedule',
        'Requirements and skills needed',
        'Location or remote status',
        'How to apply and deadline',
      ],
      photoTips: [
        'Workplace photo if allowed',
        'Role poster or flyer',
      ],
      fields: [
        const CategoryField(
          key: 'role_title',
          label: 'Role title',
          hint: 'e.g. research assistant, barista',
          required: true,
        ),
        const CategoryField(
          key: 'pay_type',
          label: 'Pay type',
          hint: 'Select pay type',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['Paid', 'Unpaid', 'Stipend', 'Commission'],
        ),
        const CategoryField(
          key: 'schedule',
          label: 'Schedule',
          hint: 'e.g. weekends, 10 hrs/week',
          required: true,
        ),
        const CategoryField(
          key: 'location_type',
          label: 'Location',
          hint: 'Select location',
          required: true,
          type: CategoryFieldType.dropdown,
          options: ['On campus', 'Near campus', 'Remote', 'Hybrid'],
        ),
      ],
      priceLabel: 'Pay / stipend (GHS)',
      priceHint: 'e.g. 800/month',
      showCondition: false,
    ),
    'Other': CategoryPostingSchema(
      category: 'Other',
      kind: ListingKind.other,
      titleHint: 'Describe your item clearly in the title',
      descriptionHint:
          'Be specific about what it is, condition, and what is included.',
      descriptionChecklist: [
        'What exactly is being sold',
        'Condition and age',
        'What is included',
        'Reason for selling',
        'Pickup or delivery notes',
        'Any defects honestly disclosed',
      ],
      photoTips: [
        'Clear photo of the full item',
        'Close-up of important details',
        'Accessories included',
      ],
      fields: [
        const CategoryField(
          key: 'item_summary',
          label: 'Item summary',
          hint: 'One line summary of what this is',
          required: true,
        ),
      ],
      priceLabel: 'Price (GHS)',
      priceHint: 'e.g. 50',
    ),
  };

  static List<String> get allCategoryNames => MarketCategories.listingCategories;
}
